on:
# push:
#   branches: [main, master]
# schedule:
#   - cron: '0 6 * * *'
 workflow_dispatch:

name: Build dashboard

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
      - name: Install system dependencies
        run: |
          sudo apt install libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          lapply(c("tidyr", "dplyr", "flexdashboard", "kableExtra", "heddlr", "remotes"), install.packages)
          remotes::install_github("ropensci/cchecks")
        shell: Rscript {0}

      - name: Deploy package
        run: |
          readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
          readonly local was_build=$(echo "$last_commit_log" | grep -c "Automated build" )
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'knitr::purl("build.Rmd")'
          Rscript build.R
          if [[ "$was_build" -eq 0 ]]; then
              git add index.html
              git commit -m "Automated build"
              git push
          else
              git add index.html
              git commit --amend -m "Automated build"
              git push -f
          fi
          
